<?php

namespace Nitro\Container;

use Nitro\Container\Attributes\ProcessScoped;
use Nitro\Container\Attributes\RequestScoped;
use Nitro\Container\Contracts\ContainerInterface;
use Nitro\Container\Exceptions\LifetimeException;
use Nitro\Container\Exceptions\NotFoundException;
use ReflectionClass;
use ReflectionNamedType;
use RuntimeException;
use SplObjectStorage;

/**
 * The Nitro service container — a reflection-based dependency-injection container.
 *
 * Holds service definitions (closures, class-strings, or pre-built instances) and
 * resolves them on demand, auto-wiring constructor dependencies via cached
 * reflection. Supports singletons, request-scoped bindings (flushed between worker
 * requests), factories, aliases, contextual and tagged bindings, lazy deferred-
 * provider registration, and route-model parameter binding.
 */
class Container implements ContainerInterface, \ArrayAccess
{
    use Concerns\FiresResolutionCallbacks;
    use Concerns\ManagesBindings;


    private array $tags = [];
    private array $contextualBindings = [];
    private array $building = [];

    /**
     * Map of alias => target abstract, recorded by alias(). Lets forgetScoped()
     * clear the instance an alias actually resolves to (cached under the target
     * name), not just the alias key — see forgetScoped().
     */
    private array $aliasTargets = [];

    /**
     * Abstracts registered as request-scoped via scoped(). Unlike the central
     * WorkerMode list, a feature declares its own bindings scoped at register
     * time; forgetScopedInstances() flushes them all between worker requests.
     * (Same model as Laravel Octane's scoped instances.)
     */
    private array $scopedInstances = [];

    /**
     * Callback invoked when an unregistered abstract is requested. Used by
     * Application to lazy-register deferred service providers — when their
     * service is finally asked for, we call them in, register their bindings,
     * and resolve as normal.
     *
     * Signature: fn(string $abstract): bool — returns true if the abstract is
     * now registered (so the caller can retry the lookup).
     */
    private ?\Closure $deferredResolver = null;

    /**
     * Sentinel returned by a parameter binder to mean "I don't handle this
     * type" — the resolver then falls through to its normal logic. Null-byte
     * prefixed so it can never collide with a real resolved value.
     */
    public const PARAM_UNRESOLVED = "\0nitro:param-unresolved";

    /**
     * Optional resolver that turns a typed parameter + a matching scalar route
     * value into an object (route-model binding). Registered by the routing
     * layer so the core container stays free of any model/HTTP dependency.
     * Signature: fn(string $typeName, mixed $scalar): mixed — return
     * PARAM_UNRESOLVED to decline.
     */
    private ?\Closure $parameterBinder = null;

    /**
     * Per-class reflection cache. Each entry is:
     *   [
     *     'class'   => ReflectionClass,
     *     'instantiable' => bool,
     *     'ctor'    => ReflectionMethod|null,
     *     'params'  => ReflectionParameter[],   // empty when ctor is null
     *   ]
     *
     * Populated lazily by build() so each class pays the reflection cost
     * exactly once for the lifetime of the container instance.
     */
    private array $reflectionCache = [];

    /**
     * Cached ReflectionMethod + parameter metadata for call() targets, keyed by
     * "Class::method". Controller dispatch goes through call() on every request;
     * without this each dispatch rebuilds a ReflectionMethod and re-materializes
     * its ReflectionParameter objects. Methods are stateless w.r.t. the instance,
     * so one cache entry serves every future invocation.
     *
     * @var array<string, array{reflector: \ReflectionMethod, params: array}>
     */
    private array $callableCache = [];

    /**
     * AOT-compiled resolution factories, keyed by class name. Each is a
     * closure `fn($container): object` that builds the class with its whole
     * autowire graph inlined (bound deps deferred to the container) — no
     * reflection at runtime. Generated by `nitro optimize` and loaded in
     * production via {@see setCompiledFactories()}; empty in dev, where the
     * container always reflects so code changes take effect without recompiling.
     *
     * @var array<string, \Closure>
     */
    private array $compiledFactories = [];

    // ============================================
    // SINGLETON
    // ============================================

    private static ?self $instance = null;

    /** Public so tests can create isolated containers instead of the shared singleton. */
    public function __construct() {}

    public static function getInstance(): self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    public static function reset(): void
    {
        self::$instance = null;
    }

    /**
     * Make this the container the helpers and facades resolve from, returning
     * the one it replaces.
     *
     * For a host that owns more than one application in a process: a test
     * harness running one test against a throwaway application and the next
     * against a shared one, or a worker handing off between them. reset()
     * cannot serve that purpose — it forgets the instance rather than
     * exchanging it, leaving anything that still holds the previous
     * application resolving from a container nothing else can reach.
     */
    public static function setInstance(?self $container): ?self
    {
        $previous = self::$instance;

        self::$instance = $container;

        return $previous;
    }

    // ============================================
    // REGISTRY
    // Stores and retrieves services by name
    // ============================================

    /** Registered service definitions */
    private array $services = [];

    /** Resolved singleton instances */
    private array $resolved = [];

    /**
     * How long each binding lives, keyed by name.
     *
     * Recorded at bind time so a resolution can tell whether it is about to
     * hand a short-lived object to a long-lived one. Aliases hold no entry:
     * they resolve through to their target, which is the only thing with a
     * lifetime to have an opinion about.
     *
     * @var array<string, Lifetime>
     */
    private array $lifetimes = [];

    /**
     * Answers from lifetimeOf(), which reads attributes by reflection.
     *
     * @var array<string, Lifetime>
     */
    private array $lifetimeMemo = [];

    /**
     * Record how long a name lives without binding anything to it.
     *
     * For a service supplied from outside the container rather than built by
     * it — the request, which the kernel hands over with instance() once per
     * request. Its lifetime has to be known before the first one exists, or
     * everything resolved during boot reads it as having no lifetime at all
     * and is free to hold on to it.
     */
    public function declareLifetime(string $name, Lifetime $lifetime): void
    {
        $this->lifetimes[$name] = $lifetime;
        unset($this->lifetimeMemo[$name]);
    }

    /**
     * Request-lived objects handed out since the last reset, by generation.
     *
     * Only populated while capture detection is on; see capturedRequestState().
     *
     * @var SplObjectStorage<object, int>|null
     */
    private ?SplObjectStorage $requestScopedInstances = null;

    /** Which request is current, counted rather than named: only equality matters. */
    private int $requestGeneration = 0;

    private bool $detectsCapturedState = false;

    /**
     * Record request-lived objects so that capturedRequestState() can find any
     * still held after the request ends.
     *
     * Off by default: it keeps a reference to every request-scoped object for
     * the length of a request and the scan reflects over the whole long-lived
     * object graph. Worth it in a test suite and on a developer's worker, not
     * in production.
     */
    public function detectCapturedState(bool $detect): void
    {
        $this->detectsCapturedState = $detect;
        $this->requestScopedInstances = $detect ? new SplObjectStorage() : null;
    }

    /**
     * Request-scoped objects still reachable from something that outlives them.
     *
     * Call before dropping the scoped instances, or there is nothing left to
     * find. Returns an empty array when detection is off.
     *
     * @return array<int, array{holder: string, path: string, captured: string}>
     */
    public function capturedRequestState(): array
    {
        if ($this->requestScopedInstances === null) {
            return [];
        }

        $longLived = [];

        foreach ($this->resolved as $name => $instance) {
            if ($this->lifetimeOf($name) === Lifetime::Process) {
                $longLived[$name] = $instance;
            }
        }

        $opaque = new SplObjectStorage();
        $opaque->attach($this);

        return (new CapturedStateScanner($this->requestScopedInstances, $this->requestGeneration, $opaque))
            ->scan($longLived);
    }

    /**
     * Note that a request has ended, so objects built during the next one are
     * not mistaken for the ones this scan was looking for.
     */
    public function startNewRequestGeneration(): void
    {
        $this->requestGeneration++;
        $this->requestScopedInstances = $this->detectsCapturedState ? new SplObjectStorage() : null;
    }

    /** Tag an object as belonging to the current request, if it is one. */
    private function noteRequestScoped(string $name, mixed $instance): void
    {
        if ($this->requestScopedInstances === null || ! is_object($instance)) {
            return;
        }

        if ($this->lifetimeOf($name) === Lifetime::Request) {
            $this->requestScopedInstances[$instance] = $this->requestGeneration;
        }
    }

    /**
     * How long a name lives once resolved.
     *
     * The class's own attribute wins over the binding, so a service cannot be
     * registered as a singleton in one provider and as scoped in another and
     * have the container believe both. An alias has no lifetime of its own and
     * answers for its target.
     */
    public function lifetimeOf(string $name): Lifetime
    {
        if (isset($this->lifetimeMemo[$name])) {
            return $this->lifetimeMemo[$name];
        }

        $target = $this->aliasTargets[$name] ?? $name;

        return $this->lifetimeMemo[$name] = $this->lifetimeAttributeOf($target)
            ?? $this->lifetimes[$target]
            ?? Lifetime::Transient;
    }

    private function lifetimeAttributeOf(string $class): ?Lifetime
    {
        if (! class_exists($class)) {
            return null;
        }

        $reflection = new ReflectionClass($class);

        if ($reflection->getAttributes(RequestScoped::class) !== []) {
            return Lifetime::Request;
        }

        if ($reflection->getAttributes(ProcessScoped::class) !== []) {
            return Lifetime::Process;
        }

        return null;
    }

    /** Bind a service or value */
    public function bind(string $name, $value, bool $singleton = true): void
    {
        $rebinding = isset($this->services[$name]);

        $this->services[$name] = [
            'value'     => $value,
            'singleton' => $singleton,
        ];
        $this->lifetimes[$name] = $singleton ? Lifetime::Process : Lifetime::Transient;
        unset($this->resolved[$name], $this->lifetimeMemo[$name]);

        if ($rebinding) {
            $this->fireRebound($name);
        }
    }

    /**
     * Register a request-scoped service: resolved once like a singleton, but
     * flushed by forgetScopedInstances() between worker requests. The binding
     * declares its own lifecycle — no central reset list to edit per feature.
     */
    public function scoped(string $name, $value = null): void
    {
        if (!in_array($name, $this->scopedInstances, true)) {
            $this->scopedInstances[] = $name;
        }
        $this->singleton($name, $value);

        // After singleton(), which binds as Process: scoped is a singleton in
        // how it resolves and a request in how long it survives.
        $this->lifetimes[$name] = Lifetime::Request;
        unset($this->lifetimeMemo[$name]);
    }

    /**
     * Drop the resolved instance of every scoped binding (and any alias target
     * it resolves to) so the next worker request rebuilds them fresh.
     */
    public function forgetScopedInstances(): void
    {
        foreach ($this->scopedInstances as $name) {
            unset($this->resolved[$name]);
            if (isset($this->aliasTargets[$name])) {
                unset($this->resolved[$this->aliasTargets[$name]]);
            }
        }
    }

    /** Register a singleton service */
    public function singleton(string $name, $value = null): void
    {
        $this->bind($name, $value ?? $name, true);

    }

    /** Register an already-created instance */
    public function instance(string $name, mixed $instance): void
    {
        $rebinding = isset($this->services[$name]);

        $this->resolved[$name] = $instance;
        $this->services[$name] = [
            'value'     => $instance,
            'singleton' => true,
        ];
        $this->lifetimes[$name] = Lifetime::Process;
        unset($this->lifetimeMemo[$name]);

        // The request arrives this way, and its lifetime is declared rather
        // than implied by the binding — so ask, instead of assuming Process.
        $this->noteRequestScoped($name, $instance);


        if ($rebinding) {
            $this->fireRebound($name, $instance);
        }
    }

    /** Register a factory (non-singleton) */
    public function factory(string $name, callable $factory): void
    {
        $this->bind($name, $factory, false);
    }

    /**
     * Register a resolver that gets a chance to register a service on demand
     * when get()/make() can't find it. Used by the deferred-provider path.
     */
    public function setDeferredResolver(\Closure $resolver): void
    {
        $this->deferredResolver = $resolver;
    }

    /**
     * Register the parameter binder used for route-model binding. See
     * {@see $parameterBinder}.
     */
    public function bindParametersUsing(\Closure $resolver): void
    {
        $this->parameterBinder = $resolver;
    }

    /** Get a registered service by name */
    public function get(string $name): mixed
    {
        if (!$this->has($name)) {
            if ($this->deferredResolver !== null && ($this->deferredResolver)($name)) {
                // Provider registered the binding lazily — fall through.
            } else {
                throw new NotFoundException("Service [{$name}] not found in container");
            }
        }

        $service = $this->services[$name];

        if ($service['singleton'] && isset($this->resolved[$name])) {
            return $this->resolved[$name];
        }

        // Guarded inline rather than inside the fire methods: most applications
        // register no hooks, and those that do register them against a handful
        // of services. Calling a method only for it to return immediately still
        // costs a call per resolution, once per class in an auto-wired graph.
        if ($this->shouldFireCallbacks($name)) {
            $this->fireBeforeResolving($name);
            $resolved = $this->fireResolved($name, $this->resolveValue($service['value']));
        } else {
            $resolved = $this->resolveValue($service['value']);
        }

        if ($service['singleton']) {
            $this->resolved[$name] = $resolved;
        }

        $this->noteRequestScoped($name, $resolved);

        return $resolved;
    }

    /** Check if a service is registered */
    public function has(string $name): bool
    {
        return isset($this->services[$name]);
    }

    /** Get a service or return default if not found */
    public function getOrDefault(string $name, $default = null): mixed
    {
        if (!$this->has($name)) {
            return $default;
        }
        return $this->get($name);
    }

    /** Remove a service from the registry */
    public function forget(string $name): void
    {
        unset($this->services[$name]);
        unset($this->resolved[$name]);
        unset($this->aliasTargets[$name]);
    }

    /**
     * Drop the RESOLVED instance for each scoped service so the next request
     * gets a fresh one, while keeping the binding in place so provider
     * singletons can re-instantiate without re-running their providers.
     *
     * For services bound via instance() (e.g. the current Request), the Kernel
     * re-binds via instance() at the start of the next request — clearing
     * resolved is enough because that re-binding overwrites both arrays.
     */
    public function forgetScoped(array $names): void
    {
        foreach ($names as $name) {
            unset($this->resolved[$name]);

            // Aliased scoped services (e.g. 'auth' → SessionGuard) cache their
            // resolved instance under the TARGET class name, not the alias key.
            // Clear that too — otherwise the underlying singleton survives the
            // reset and leaks request state across worker iterations.
            if (isset($this->aliasTargets[$name])) {
                unset($this->resolved[$this->aliasTargets[$name]]);
            }
        }
    }

    /**
     * Drop both the resolved instance AND the binding. Useful when the caller
     * wants has() to return false until something re-binds.
     */
    public function forgetScopedHard(array $names): void
    {
        foreach ($names as $name) {
            unset($this->resolved[$name]);
            unset($this->services[$name]);
        }
    }

    /** Resolve a raw value — executes closures, returns everything else as-is */
    private function resolveValue($value): mixed
    {
        if ($value instanceof \Closure) {
            return $value($this);
        }

        if (is_string($value) && class_exists($value)) {
            // Prevent infinite loop: if we're already resolving this class, just build it directly
            if (isset($this->building[$value])) {
                return $this->build($value);
            }

            $this->building[$value] = true;
            try {
                return $this->make($value);
            } finally {
                unset($this->building[$value]);
            }
        }

        return $value;
    }

    // ============================================
    // AUTO-WIRING
    // Resolves class dependencies via reflection
    // ============================================

    /** Classes currently being resolved — used to detect circular dependencies */
    private array $resolving = [];

    /**
     * Get an instance of $abstract: RESOLVE the registered binding if there is
     * one, otherwise CREATE it by reflecting its constructor and auto-wiring the
     * dependencies. The name says exactly that, which is why it is the method to
     * reach for — {@see make()} is the same thing under the older name.
     *
     * This is the everyday way to ask the container for something. Contrast
     * {@see get()}, which is a strict registry lookup: it resolves a binding and
     * throws NotFoundException when none exists, never auto-wiring. Use get()
     * only when an unregistered name is a bug you want to hear about (a service
     * name coming from config, say); use createOrResolve() for everything else.
     *
     * Only delegates to get() when no $parameters are passed, so explicit
     * overrides are never silently dropped.
     */
    public function createOrResolve(string $abstract, array $parameters = []): mixed
    {
        if (empty($parameters)) {
            if ($this->has($abstract)) {
                return $this->get($abstract);
            }
            // AOT fast path: a compiled factory inlines the whole autowire graph,
            // so we skip reflection entirely. Only used for a plain resolution
            // (no overrides); overrides fall through to the reflective builder.
            if (isset($this->compiledFactories[$abstract])) {
                return ($this->compiledFactories[$abstract])($this);
            }
            // Give a deferred-provider resolver a chance to register this
            // abstract before we fall back to auto-wiring.
            if ($this->deferredResolver !== null && ($this->deferredResolver)($abstract)) {
                return $this->get($abstract);
            }
        }

        return $this->build($abstract, $parameters);
    }

    /**
     * Alias of {@see createOrResolve()}, kept because it is the name the wider
     * PHP world (and a lot of existing application code) reaches for first.
     * Identical behaviour — pick whichever reads better in context; the
     * framework's own code standardises on createOrResolve().
     */
    public function make(string $abstract, array $parameters = []): mixed
    {
        return $this->createOrResolve($abstract, $parameters);
    }

    /** Build a class via reflection, resolving all constructor dependencies recursively */
    public function build(string $abstract, array $parameters = []): mixed
    {
        if ($this->shouldFireCallbacks($abstract)) {
            $this->fireBeforeResolving($abstract, $parameters);
        }

        if (isset($this->resolving[$abstract])) {
            $chain = implode(' → ', array_keys($this->resolving)) . ' → ' . $abstract;
            throw new RuntimeException("Circular dependency detected: {$chain}");
        }

        $meta = $this->reflectionMetaFor($abstract);

        if (!$meta['instantiable']) {
            throw new RuntimeException("Class [{$abstract}] is not instantiable. Is it an interface or abstract class?");
        }

        if ($meta['ctor'] === null) {
            // Cheaper than newInstanceArgs([]) for a parameterless class.
            $instance = new $abstract();

            return $this->shouldFireCallbacks($abstract) ? $this->fireResolved($abstract, $instance) : $instance;
        }

        $this->resolving[$abstract] = true;

        try {
            $dependencies = $this->resolveDependencies($abstract, $meta['params'], $parameters);
            $instance = $meta['class']->newInstanceArgs($dependencies);
        } finally {
            unset($this->resolving[$abstract]);
        }

        return $this->shouldFireCallbacks($abstract) ? $this->fireResolved($abstract, $instance) : $instance;
    }

    /**
     * Return cached reflection metadata for a class, populating the cache on
     * first call. Each class then pays the reflection cost exactly once.
     *
     * @return array{class: ReflectionClass, instantiable: bool, ctor: \ReflectionMethod|null, params: array}
     */
    private function reflectionMetaFor(string $abstract): array
    {
        if (isset($this->reflectionCache[$abstract])) {
            return $this->reflectionCache[$abstract];
        }

        try {
            $normalized = ltrim($abstract, '\\');
            $reflector = new ReflectionClass($normalized);
        } catch (\ReflectionException $exception) {
            throw new RuntimeException("Class [{$abstract}] does not exist. (Tried resolving as [{$normalized}])");
        }

        $ctor = $reflector->getConstructor();

        return $this->reflectionCache[$abstract] = [
            'class'        => $reflector,
            'instantiable' => $reflector->isInstantiable(),
            'ctor'         => $ctor,
            'params'       => $ctor ? $ctor->getParameters() : [],
        ];
    }

    /** Drop the reflection cache (test harnesses, opcache reset on deploy). */
    public function clearReflectionCache(): void
    {
        $this->reflectionCache = [];
        $this->callableCache = [];
    }

    /** Install the AOT-compiled factory map (from `nitro optimize`). @param array<string,\Closure> $factories */
    public function setCompiledFactories(array $factories): void
    {
        $this->compiledFactories = $factories;
    }

    /**
     * Whether a class has any contextual binding registered against it. The
     * container compiler consults this to SKIP compiling such classes — a
     * generated factory can't honour a contextual override, so those fall back
     * to the reflective builder.
     */
    public function hasContextualBindings(string $consumer): bool
    {
        return isset($this->contextualBindings[$consumer]);
    }

    /**
     * Resolve constructor parameters — auto-wires classes, handles primitives and defaults.
     *
     * Resolution order per parameter: contextual binding (by param name, then by
     * type) → named override → positional override → auto-wired class → default
     * value. Contextual bindings are keyed by both parameter name and type name.
     *
     * @param string|null $consumer The class being built (null when called from call())
     */
    private function resolveDependencies(?string $consumer, array $reflectionParams, array $primitives = []): array
    {
        $dependencies = [];
        $numericIndex = 0;

        foreach ($reflectionParams as $param) {
            $name = $param->getName();
            $type = $param->getType();

            // getDeclaringClass() returns null for closures passed to call()
            $declaringClass = $param->getDeclaringClass();
            $class = $declaringClass ? $declaringClass->getName() : null;

            // The consumer is the class we're building — prefer it over declaring class
            // (declaring class may be a parent, consumer is the actual concrete)
            $contextKey = $consumer ?? $class;

            $typeName = ($type instanceof ReflectionNamedType && !$type->isBuiltin())
                ? $type->getName()
                : null;

            // -------------------------------------------------------
            // 1. Contextual bindings (checked first)
            //    Check by parameter name, then by type name
            // -------------------------------------------------------
            if ($contextKey !== null) {
                // Check by parameter name: contextual('Controller', 'logger', SpecialLogger::class)
                if (isset($this->contextualBindings[$contextKey][$name])) {
                    $value = $this->contextualBindings[$contextKey][$name];
                    $dependencies[] = $value instanceof \Closure ? $value($this) : $this->resolveContextualValue($value);
                    continue;
                }

                // Check by type/interface name: contextual('Controller', LoggerInterface::class, FileLogger::class)
                if ($typeName !== null && isset($this->contextualBindings[$contextKey][$typeName])) {
                    $value = $this->contextualBindings[$contextKey][$typeName];
                    $dependencies[] = $value instanceof \Closure ? $value($this) : $this->resolveContextualValue($value);
                    continue;
                }
            }

            // -------------------------------------------------------
            // 1b. Route-model binding: a typed (class) parameter whose name
            //     matches a scalar route value is handed to the binder, which
            //     may resolve it to an object (e.g. Model::find()). Declining
            //     (PARAM_UNRESOLVED) falls through to the scalar override below.
            // -------------------------------------------------------
            if (
                $typeName !== null
                && $this->parameterBinder !== null
                && array_key_exists($name, $primitives)
                && is_scalar($primitives[$name])
            ) {
                $bound = ($this->parameterBinder)($typeName, $primitives[$name]);
                if ($bound !== self::PARAM_UNRESOLVED) {
                    $dependencies[] = $bound;
                    continue;
                }
            }

            // -------------------------------------------------------
            // 2. Named overrides (explicit parameters passed to make/build)
            // -------------------------------------------------------
            if (array_key_exists($name, $primitives)) {
                $dependencies[] = $primitives[$name];
                continue;
            }

            // -------------------------------------------------------
            // 3. Numeric overrides (e.g. route params)
            //
            //    A class-typed parameter is a dependency to be resolved, not a
            //    route segment — so a positional value is only handed to one
            //    when the binder can turn it into that class (route-model
            //    binding by position). Otherwise the position is left for the
            //    next scalar parameter and the type is auto-wired below.
            //
            //    Without that distinction, __invoke(string $code, Renderer $r)
            //    gets the route's second value in $r and dies on a type error,
            //    which is a confusing way to learn that a controller may not
            //    ask the container for anything after a route parameter.
            // -------------------------------------------------------
            if (array_key_exists($numericIndex, $primitives)) {
                $value = $primitives[$numericIndex];

                if ($typeName === null || $value instanceof $typeName) {
                    $dependencies[] = $value;
                    $numericIndex++;
                    continue;
                }

                if ($this->parameterBinder !== null && is_scalar($value)) {
                    $bound = ($this->parameterBinder)($typeName, $value);

                    if ($bound !== self::PARAM_UNRESOLVED) {
                        $dependencies[] = $bound;
                        $numericIndex++;
                        continue;
                    }
                }
            }

            // -------------------------------------------------------
            // 4. Auto-wire class/interface types
            // -------------------------------------------------------
            if ($typeName !== null) {
                // Closure can't be auto-wired
                if ($typeName === 'Closure') {
                    if ($param->isDefaultValueAvailable()) {
                        $dependencies[] = $param->getDefaultValue();
                        continue;
                    }
                    throw new RuntimeException(
                        "Cannot auto-wire Closure parameter [\${$name}]" .
                        ($class ? " in [{$class}]" : '') .
                        ". Use a factory binding."
                    );
                }

                $dependencies[] = $this->make($typeName);
                continue;
            }

            // -------------------------------------------------------
            // 5. Default values
            // -------------------------------------------------------
            if ($param->isDefaultValueAvailable()) {
                $dependencies[] = $param->getDefaultValue();
                continue;
            }

            throw new RuntimeException(
                "Cannot resolve parameter [{$name}]" .
                ($class ? " in [{$class}]" : '') .
                " — no rule defined."
            );
        }

        return $dependencies;
    }

    /**
     * Resolve a contextual binding value.
     * If it's a class string, make it. Otherwise return as-is.
     */
    private function resolveContextualValue(mixed $value): mixed
    {
        if (is_string($value) && class_exists($value)) {
            return $this->make($value);
        }
        return $value;
    }

    // ============================================
    // DEBUGGING
    // ============================================

    /** Get all registered service names */
    public function getServiceNames(): array
    {
        return array_keys($this->services);
    }

    /** Get all currently resolved instances */
    public function getResolvedInstances(): array
    {
        return $this->resolved;
    }

    /**
     * Every registered binding, as name => the value it was bound to.
     *
     * For tooling that inspects the container without resolving anything —
     * resolving is what an audit of the bindings is trying to avoid, since a
     * factory may open a connection or read the request.
     *
     * @return array<string, mixed>
     */
    public function registeredBindings(): array
    {
        return array_map(static fn (array $service): mixed => $service['value'], $this->services);
    }

    /**
     * Alias name => the abstract it resolves to.
     *
     * @return array<string, string>
     */
    public function registeredAliases(): array
    {
        return $this->aliasTargets;
    }

    /** Force-resolve all services and return instances */
    public function resolveAllForDebug(): array
    {
        foreach ($this->services as $name => $service) {
            $this->get($name);
        }
        return $this->resolved;
    }

    /**
     * Return structured constructor-introspection data for an abstract
     * (for debugging container resolution); never echoes or dies.
     */
    public function debugReflection(string $abstract): array
    {
        try {
            $reflector = new ReflectionClass($abstract);
            $constructor = $reflector->getConstructor();

            $info = [
                'class' => $abstract,
                'file'  => $reflector->getFileName(),
                'parameters' => [],
            ];

            if (!$constructor) {
                return $info;
            }

            foreach ($constructor->getParameters() as $param) {
                $type = $param->getType();
                $paramInfo = [
                    'name'       => $param->getName(),
                    'type_class' => $type ? get_class($type) : null,
                    'type_name'  => null,
                    'is_builtin' => null,
                    'has_default' => $param->isDefaultValueAvailable(),
                ];

                if ($type instanceof ReflectionNamedType) {
                    $paramInfo['type_name'] = $type->getName();
                    $paramInfo['is_builtin'] = $type->isBuiltin();
                }

                $info['parameters'][] = $paramInfo;
            }

            return $info;
        } catch (\Exception $exception) {
            return ['error' => $exception->getMessage()];
        }
    }

    // ============================================
    // MAGIC ACCESS
    // ============================================

    public function __get(string $name): mixed
    {
        return $this->get($name);
    }

    public function __isset(string $name): bool
    {
        return $this->has($name);
    }

    public function tag(string $tag, string ...$abstracts): void
    {
        foreach ($abstracts as $abstract) {
            $this->tags[$tag][] = $abstract;
        }
    }

    public function tagged(string $tag): array
    {
        if (!isset($this->tags[$tag])) {
            return [];
        }
        $result = [];
        foreach ($this->tags[$tag] as $abstract) {
            $result[] = $this->make($abstract);
        }
        return $result;
    }

    /**
     * Register a contextual binding.
     *
     * $needed can be a parameter name OR an interface/class name.
     * Examples:
     *   contextual(Controller::class, LoggerInterface::class, FileLogger::class)
     *   contextual(Controller::class, 'diskPath', '/tmp/uploads')
     */
    public function contextual(string $needer, string $needed, string|callable $concrete): void
    {
        $this->contextualBindings[$needer][$needed] = $concrete;
    }

    /**
     * Invoke a callable (closure or [object, method]), auto-wiring its
     * parameters. Passes null as consumer since call() operates on
     * closures/methods, not class construction.
     */
    public function call(callable $callable, array $parameters = []): mixed
    {
        if (is_array($callable)) {
            [$object, $method] = $callable;

            // Cache the ReflectionMethod + its parameter list per Class::method.
            // The reflector is instance-independent, so invokeArgs() below can
            // reuse it for any instance — the controller-dispatch hot path then
            // skips ReflectionMethod construction entirely after the first hit.
            $key = (is_object($object) ? $object::class : $object) . '::' . $method;
            $meta = $this->callableCache[$key]
                ??= (static function () use ($object, $method): array {
                    $reflector = new \ReflectionMethod($object, $method);
                    return ['reflector' => $reflector, 'params' => $reflector->getParameters()];
                })();

            $dependencies = $this->resolveDependencies(null, $meta['params'], $parameters);

            return $meta['reflector']->invokeArgs($object, $dependencies);
        }

        $reflector = new \ReflectionFunction($callable);
        $dependencies = $this->resolveDependencies(null, $reflector->getParameters(), $parameters);

        return $reflector->invokeArgs($dependencies);
    }

    /** Register an alias that resolves to an existing binding */
    /**
     * Register a second name for an existing binding.
     *
     * The alias resolves through to the target every time rather than caching
     * anything of its own. Caching here silently promotes whatever it points at
     * to a singleton: alias(Guard::class, 'auth') over a scoped 'auth' handed
     * out the first request's guard for the life of the worker, still holding
     * that request's session. Visitor two was signed in as visitor one, or —
     * as it actually surfaced — signed in according to auth() and signed out
     * according to the middleware, because one read the alias and one read the
     * target.
     *
     * So: never a singleton, whatever the target is. The target's own binding
     * decides the lifetime, which is the only place that decision belongs.
     */
    /**
     * The name callbacks, extenders and instances are keyed under.
     *
     * An alias and its target must agree, or a hook registered against one
     * would never fire for the other.
     */
    protected function normalizeAbstract(string $abstract): string
    {
        return $this->aliasTargets[$abstract] ?? $abstract;
    }

    public function alias(string $alias, string $abstract): void
    {
        $this->aliasTargets[$alias] = $abstract;
        $this->services[$alias] = [
            'value'     => fn($container) => $container->get($abstract),
            'singleton' => false,
        ];
    }
}