<?php

namespace Nitro\Container;

use Closure;
use ReflectionClass;
use ReflectionNamedType;
use ReflectionParameter;

/**
 * Ahead-of-time container compiler (the `nitro optimize` "compiled container").
 *
 * Given a set of entry classes (bound class-string services + route controllers
 * + middleware), it emits a PHP file returning a map of
 *   [ class => static fn($c) => new \Class(...inlined graph...) ]
 * so production resolves those classes with ZERO runtime reflection — the
 * container just calls the closure (see {@see Container::$compiledFactories}).
 *
 * Rules that keep it correct:
 *   - A dependency that is BOUND, an interface/abstract, or that we can't fully
 *     inline is deferred to `$c->make(Dep::class)` — so bindings, aliases,
 *     singletons and deferred providers still apply.
 *   - Only UNBOUND, instantiable, contextual-free concrete classes are inlined
 *     (recursively). Anything we can't compile is simply dropped from the map,
 *     and the container falls back to reflection for it. The compiled map is a
 *     pure accelerator — never the only path.
 */
class ContainerCompiler
{
    /**
     * @param array<int, class-string> $entryClasses
     * @return string PHP source returning array<string, Closure>.
     */
    public function compile(Container $container, array $entryClasses): string
    {
        $entries = [];

        foreach (array_unique($entryClasses) as $class) {
            try {
                $expr = $this->newExpr($container, $class, []);
                if ($expr !== null) {
                    $entries[$class] = $expr;
                }
            } catch (\Throwable) {
                // A class we can't reflect (bad binding, missing dep type, …) is
                // simply left out of the map — it falls back to runtime reflection.
            }
        }

        ksort($entries);

        $lines = [];
        foreach ($entries as $class => $expr) {
            $lines[] = '    ' . var_export($class, true) . ' => static fn($c) => ' . $expr . ',';
        }

        return "<?php\n\n"
            . "// Generated by `nitro optimize`. Do not edit — re-run optimize to regenerate.\n"
            . "// AOT container factories: each inlines a class's autowire graph (no runtime reflection).\n\n"
            . "return [\n" . implode("\n", $lines) . "\n];\n";
    }

    /** A `new \Class(...)` expression with fully-resolved args, or null if uncompilable. */
    private function newExpr(Container $container, string $class, array $stack): ?string
    {
        if (! class_exists($class) || in_array($class, $stack, true)) {
            return null; // missing or circular → let reflection handle it
        }

        $reflector = new ReflectionClass($class);
        if (! $reflector->isInstantiable() || $container->hasContextualBindings($class)) {
            return null;
        }

        $ctor = $reflector->getConstructor();
        if ($ctor === null) {
            return "new \\{$class}()";
        }

        $args = [];
        foreach ($ctor->getParameters() as $param) {
            $arg = $this->argExpr($container, $param, [...$stack, $class]);
            if ($arg === null) {
                return null; // a single unresolvable param disqualifies the whole class
            }
            $args[] = $arg;
        }

        return "new \\{$class}(" . implode(', ', $args) . ')';
    }

    /** The expression that resolves one constructor parameter, or null. */
    private function argExpr(Container $container, ReflectionParameter $param, array $stack): ?string
    {
        $type = $param->getType();

        if ($type instanceof ReflectionNamedType && ! $type->isBuiltin()) {
            $name = $type->getName();

            if ($name === 'Closure' || $name === 'self' || $name === 'static' || $name === 'parent') {
                return $this->defaultExpr($param); // can't autowire — need a default
            }

            // Bound, or an interface/abstract → defer to the container so the
            // binding / alias / singleton / deferred provider still applies.
            if ($container->has($name) || ! class_exists($name) || ! (new ReflectionClass($name))->isInstantiable()) {
                return '$c->make(' . var_export($name, true) . ')';
            }

            // Unbound concrete → inline recursively; if that fails, defer at runtime.
            return $this->newExpr($container, $name, $stack)
                ?? '$c->make(' . var_export($name, true) . ')';
        }

        // Builtin / untyped → only compilable if it has a usable default.
        return $this->defaultExpr($param);
    }

    private function defaultExpr(ReflectionParameter $param): ?string
    {
        if ($param->isDefaultValueAvailable()) {
            return var_export($param->getDefaultValue(), true);
        }
        if ($param->allowsNull()) {
            return 'null';
        }
        return null;
    }
}
