<?php

namespace Nitro\Tests\Compat;

use Illuminate\Contracts\Console\Kernel as ConsoleKernel;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Attributes\Touches;
use Illuminate\Database\Eloquent\Concerns\HasEvents;
use Nitro\Database\Eloquent\CompiledModels;
use Nitro\Database\Eloquent\ModelCompiler;
use Nitro\Tests\Fixtures\Classes\Status;
use Nitro\Tests\Fixtures\Eloquent\ActiveScope;
use Nitro\Tests\Fixtures\Eloquent\Article;
use Nitro\Tests\Fixtures\Eloquent\ArticleObserver;
use Nitro\Tests\Fixtures\Eloquent\Comment;
use Nitro\Tests\Fixtures\Eloquent\CommentObserver;
use Nitro\Tests\Fixtures\Eloquent\Note;
use Nitro\Tests\Fixtures\Eloquent\Page;
use Nitro\Tests\Fixtures\Eloquent\Plain;
use Nitro\Tests\Fixtures\Eloquent\PublishedScope;
use Nitro\Tests\Fixtures\Eloquent\Tag;
use Nitro\Tests\Fixtures\Eloquent\Task;
use Nitro\Tests\Fixtures\Eloquent\Ticket;
use Nitro\Tests\TestCase;

/**
 * The compiled Eloquent Model boots models exactly as Laravel's does.
 *
 * Laravel's Model and the compiled one cannot both be loaded in one process, so the scenario
 * (tests/Fixtures/eloquent-scenario.php) runs in a fresh PHP process on each, and everything
 * booting observably did is compared: boot and initializer calls in order (with the class
 * `static::` resolved to), boot events, trait initializers, global scopes, observer listeners,
 * what each class attribute resolves to, and the table, key, incrementing and casts each
 * instance ends up with.
 */
class EloquentCompileTest extends TestCase
{
    private const MODELS = [Article::class, Comment::class, Note::class, Page::class, Plain::class, Task::class, Ticket::class];

    private string $directory;

    protected function setUp(): void
    {
        parent::setUp();

        $this->directory = sys_get_temp_dir().DIRECTORY_SEPARATOR.'nitro-eloquent-'.bin2hex(random_bytes(4));
        mkdir($this->directory);
    }

    protected function tearDown(): void
    {
        foreach (glob($this->directory.DIRECTORY_SEPARATOR.'*') ?: [] as $file) {
            @unlink($file);
        }

        @rmdir($this->directory);

        parent::tearDown();
    }

    public function test_the_installed_laravel_model_takes_every_change(): void
    {
        $compiler = new ModelCompiler;

        $this->assertNotNull($compiler->compileModel(file_get_contents(CompiledModels::laravelModelPath())));
        $this->assertSame(['bootTraits', 'initializeModelAttributes', 'resolveClassAttribute', 'resolveObserveAttributes', 'resolveGlobalScopeAttributes'], $compiler->applied);
        $this->assertSame([], $compiler->skipped);
    }

    public function test_a_method_that_differs_from_laravels_is_kept(): void
    {
        $source = file_get_contents(CompiledModels::laravelModelPath());
        $changed = str_replace('$conventionalBootMethods = array_map(', '$conventionalBootMethods = array_map(/* changed */', $source);

        $compiler = new ModelCompiler;
        $compiled = $compiler->compileModel($changed);

        $this->assertSame(['initializeModelAttributes', 'resolveClassAttribute', 'resolveObserveAttributes', 'resolveGlobalScopeAttributes'], $compiler->applied);
        $this->assertSame(['bootTraits'], $compiler->skipped);
        $this->assertStringContainsString('/* changed */', $compiled);
        $this->assertStringNotContainsString('CompiledModels::bootTraits', $compiled);
    }

    public function test_a_source_with_no_known_method_is_not_compiled(): void
    {
        $this->assertNull((new ModelCompiler)->compileModel("<?php\n\nclass Model\n{\n}\n"));
    }

    public function test_the_compiled_model_is_laravels_with_only_the_listed_changes(): void
    {
        $laravel = str_replace("\r\n", "\n", file_get_contents(CompiledModels::laravelModelPath()));
        $compiled = str_replace("\r\n", "\n", (new ModelCompiler)->compileModel($laravel));

        $restored = str_replace(
            [
                "// Generated by `php artisan eloquent:cache` (Nitro) from Laravel's Model. Do not edit.\n\n",
                "        if (\\Nitro\\Database\\Eloquent\\CompiledModels::bootTraits(\$class, static::\$traitInitializers)) {\n            return;\n        }\n\n",
                "        [\$declaresTable, \$hasTableAttribute] = \\Nitro\\Database\\Eloquent\\CompiledModels::tableDeclaration(static::class);\n\n        if (! \$declaresTable && \$hasTableAttribute) {",
                "        if ((\$instance = \\Nitro\\Database\\Eloquent\\CompiledModels::classAttribute(\$class, \$attributeClass)) !== false) {\n            return static::\$classAttributes[\$cacheKey] = \$instance === null ? null : (\$property ? \$instance->{\$property} : \$instance);\n        }\n\n",
            ],
            [
                '',
                '',
                "        \$reflection = new ReflectionClass(static::class);\n\n        \$declaresTable = \$reflection->hasProperty('table')\n            && \$reflection->getProperty('table')->getDeclaringClass()->getName() === static::class;\n\n        if (! \$declaresTable && \$reflection->getAttributes(Table::class) !== []) {",
                '',
            ],
            $compiled
        );

        /** The trait-method overrides are added at the end of the class. */
        $overrides = strpos($restored, "\n    /**\n     * HasEvents::resolveObserveAttributes(), from Nitro's compiled plan");
        $this->assertNotFalse($overrides);
        $restored = substr($restored, 0, $overrides)."}\n";

        $this->assertSame($laravel, $restored);
    }

    public function test_a_trait_method_that_differs_from_laravels_is_not_overridden(): void
    {
        $compiler = new ModelCompiler;
        $compiled = $compiler->compileModel(file_get_contents(CompiledModels::laravelModelPath()), [
            HasEvents::class => '<?php trait HasEvents { public static function resolveObserveAttributes() { return []; } }',
        ]);

        $this->assertSame(['resolveObserveAttributes'], $compiler->skipped);
        $this->assertStringNotContainsString('function resolveObserveAttributes(', $compiled);
        $this->assertStringContainsString('function resolveGlobalScopeAttributes(', $compiled);
    }

    public function test_observers_and_scopes_are_resolved_as_laravel_resolves_them(): void
    {
        $plans = ModelCompiler::plans([dirname(__DIR__).'/Fixtures/Eloquent']);

        $this->assertSame([ArticleObserver::class, CommentObserver::class], $plans[Comment::class][3]);
        $this->assertSame([ActiveScope::class, PublishedScope::class], $plans[Article::class][4]);
        $this->assertSame([ActiveScope::class], $plans[Note::class][4]);
        $this->assertNull($plans[Ticket::class][3], 'A model resolving its own observers keeps doing so.');
        $this->assertNull($plans[Task::class][3], 'So do its children, which inherit its method.');
        $this->assertSame([], $plans[Ticket::class][4]);
    }

    public function test_plans_follow_laravels_boot_order_for_every_model(): void
    {
        $plans = ModelCompiler::plans([dirname(__DIR__).'/Fixtures/Eloquent']);

        $this->assertSame(self::MODELS, array_keys($plans));
        $this->assertSame(['bootSecret', 'registerAudit', 'bootPublishable', 'bootTagged', 'bootSoftDeletes', 'bootHasEvents', 'bootHasGlobalScopes'], $plans[Comment::class][0]);
        $this->assertNotContains('bootUnrelated', $plans[Ticket::class][0]);
    }

    public function test_class_attributes_are_found_where_laravel_finds_them(): void
    {
        $article = ModelCompiler::classAttributes(Article::class);
        $comment = ModelCompiler::classAttributes(Comment::class);

        $this->assertSame([Fillable::class, [['title', 'body']]], $article[strtolower(Fillable::class)]);
        $this->assertSame([Hidden::class, [['internal', 'notes']]], $comment[strtolower(Hidden::class)]);
        $this->assertSame([Tag::class, [Status::Published]], $article[strtolower(Tag::class)]);
        $this->assertArrayHasKey(strtolower(Touches::class), ModelCompiler::classAttributes(Ticket::class));
        $this->assertNull(ModelCompiler::classAttributes(Page::class));
    }

    public function test_compiled_models_boot_exactly_as_laravels(): void
    {
        [$model, $manifest] = $this->compile();

        $laravel = $this->scenario();
        $compiled = $this->scenario($model, $manifest);

        $this->assertSame(realpath($model), realpath($compiled['model']), 'The compiled Model was not loaded.');
        $this->assertSame(self::MODELS, $compiled['planned']);
        $this->assertSame(array_values(array_diff(self::MODELS, [Page::class])), $compiled['attributesCompiled']);
        $this->assertSame($laravel['observed'], $compiled['observed']);
    }

    public function test_models_without_a_plan_boot_through_laravels_code(): void
    {
        [$model, $manifest] = $this->compile(except: [Article::class, Ticket::class]);

        $compiled = $this->scenario($model, $manifest);

        $this->assertSame(realpath($model), realpath($compiled['model']));
        $this->assertNotContains(Article::class, $compiled['planned']);
        $this->assertSame($this->scenario()['observed'], $compiled['observed']);
    }

    public function test_laravels_model_loads_when_the_installed_one_is_not_the_one_compiled(): void
    {
        [$model, $manifest] = $this->compile(stamp: [0, 0]);

        $compiled = $this->scenario($model, $manifest);

        $this->assertSame(realpath(CompiledModels::laravelModelPath()), realpath($compiled['model']));
        $this->assertSame([], $compiled['planned']);
        $this->assertSame($this->scenario()['observed'], $compiled['observed']);
    }

    public function test_laravels_model_loads_when_the_caches_are_cleared_after_boot(): void
    {
        [$model, $manifest] = $this->compile();

        $compiled = $this->scenario($model, $manifest, '--cleared');

        $this->assertSame(realpath(CompiledModels::laravelModelPath()), realpath($compiled['model']));
        $this->assertSame($this->scenario()['observed'], $compiled['observed']);
    }

    public function test_eloquent_cache_compiles_the_configured_models(): void
    {
        $app = $this->bootConsole();

        $this->assertSame(0, $app->make(ConsoleKernel::class)->call('eloquent:cache'));
        $this->assertFileExists($app->getCachedEloquentModelPath());

        $manifest = require $app->getCachedEloquentPath();

        $this->assertSame(CompiledModels::stamp(CompiledModels::laravelModelPath()), $manifest['laravel']);
        $this->assertSame(self::MODELS, array_keys($manifest['plans']));
        $this->assertTrue($app->eloquentIsCached());
    }

    public function test_eloquent_cache_does_nothing_when_turned_off(): void
    {
        $app = $this->bootConsole();
        $kernel = $app->make(ConsoleKernel::class);

        $kernel->call('eloquent:cache');
        $app['config']->set('nitro.compile.eloquent', false);

        $this->assertSame(0, $kernel->call('eloquent:cache'));
        $this->assertFileDoesNotExist($app->getCachedEloquentModelPath());
        $this->assertFileDoesNotExist($app->getCachedEloquentPath());
    }

    public function test_optimize_compiles_eloquent_and_optimize_clear_removes_it(): void
    {
        $app = $this->bootConsole();
        $kernel = $app->make(ConsoleKernel::class);

        $this->assertSame(0, $kernel->call('optimize', ['--except' => 'views']));
        $this->assertFileExists($app->getCachedEloquentModelPath());
        $this->assertFileExists($app->getCachedEloquentPath());

        $this->assertSame(0, $kernel->call('optimize:clear', ['--except' => 'cache']));
        $this->assertFileDoesNotExist($app->getCachedEloquentModelPath());
        $this->assertFileDoesNotExist($app->getCachedEloquentPath());
    }

    /**
     * Compile Laravel's Model and the fixture models' plans into the test directory.
     *
     * @param  list<class-string>  $except  models left without a plan
     * @param  array{0: int, 1: int}|null  $stamp  the Laravel Model the compiled one claims to be made from
     * @return array{0: string, 1: string} [compiled Model, manifest]
     */
    private function compile(array $except = [], ?array $stamp = null): array
    {
        $laravel = CompiledModels::laravelModelPath();
        $plans = array_diff_key(ModelCompiler::plans([dirname(__DIR__).'/Fixtures/Eloquent']), array_flip($except));

        $model = $this->directory.DIRECTORY_SEPARATOR.'eloquent-model.php';
        $manifest = $this->directory.DIRECTORY_SEPARATOR.'eloquent.php';

        file_put_contents($model, (new ModelCompiler)->compileModel(file_get_contents($laravel)));
        file_put_contents($manifest, ModelCompiler::export($stamp ?? CompiledModels::stamp($laravel), $plans));

        return [$model, $manifest];
    }

    /**
     * Run the scenario in a fresh PHP process, on Laravel's Model or on the compiled one.
     */
    private function scenario(?string $model = null, ?string $manifest = null, string ...$options): array
    {
        $command = array_merge([PHP_BINARY, dirname(__DIR__).'/Fixtures/eloquent-scenario.php'], $model ? [$model, $manifest] : [], $options);
        $process = proc_open($command, [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);
        $output = stream_get_contents($pipes[1]);
        $errors = stream_get_contents($pipes[2]);
        $status = proc_close($process);

        $this->assertSame(0, $status, $errors.$output);

        return json_decode($output, true, flags: JSON_THROW_ON_ERROR);
    }
}
