<?php

namespace Nitro\View\Support;

/**
 * Disk-backed manifest of per-view flags emitted by `nitro optimize`.
 * Today it only tracks the @stream marker so the renderer doesn't have
 * to open every source file just to ask "is this a streaming view?".
 * The shape is intentionally a flat assoc map so growing it (later flags
 * like has_extends / has_fragments) is one key away.
 *
 * Loading is lazy + memoized per-process — apps that never render a
 * stream view never touch the file.
 */
class ViewManifest
{
    private const FILENAME = 'views_manifest.php';

    /** @var array<string, array<string, mixed>>|null */
    private static ?array $manifest = null;
    private static bool $loadAttempted = false;

    /**
     * Per-view flags from the manifest, or null if the manifest doesn't
     * cover this view. Callers fall back to a live source-byte probe
     * when null is returned.
     *
     * @return array<string, mixed>|null
     */
    public static function flags(string $view): ?array
    {
        return self::load()[$view] ?? null;
    }

    public static function isStream(string $view): ?bool
    {
        $flags = self::flags($view);
        return $flags === null ? null : (bool) ($flags['stream'] ?? false);
    }

    /**
     * Replace the manifest in process memory. The optimize command writes
     * the file; tests use this hook to inject without touching disk.
     *
     * @param array<string, array<string, mixed>>|null $manifest
     */
    public static function set(?array $manifest): void
    {
        self::$manifest = $manifest;
        self::$loadAttempted = true;
    }

    public static function clear(): void
    {
        self::$manifest = null;
        self::$loadAttempted = false;
        $path = self::path();
        if ($path !== null && is_file($path)) {
            @unlink($path);
        }
    }

    /**
     * Write the manifest to disk. Called by the optimize command; tests
     * can call it directly to round-trip.
     *
     * @param array<string, array<string, mixed>> $manifest
     */
    public static function write(array $manifest): bool
    {
        $path = self::path();
        if ($path === null) return false;

        $contents = "<?php\n\n// Auto-generated by `nitro optimize` — do not edit.\n\nreturn "
            . var_export($manifest, true) . ";\n";

        if (@file_put_contents($path, $contents) === false) {
            return false;
        }
        // Reset memo so next caller sees fresh data.
        self::$manifest = null;
        self::$loadAttempted = false;
        return true;
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    private static function load(): array
    {
        if (self::$loadAttempted) {
            return self::$manifest ?? [];
        }
        self::$loadAttempted = true;

        $path = self::path();
        if ($path === null || !is_file($path)) {
            return self::$manifest = [];
        }
        $data = require $path;
        return self::$manifest = is_array($data) ? $data : [];
    }

    private static function path(): ?string
    {
        try {
            return app('paths')->cache(self::FILENAME);
        } catch (\Throwable) {
            return null;
        }
    }
}
