<?php

namespace Nitro\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Nitro\Support\Opcache;
use Symfony\Component\Console\Attribute\AsCommand;

/**
 * `php artisan view:warm`: compile every Blade view (Laravel's view:cache), then, after Nitro's
 * template cache:
 *
 *  - parse-check each compiled view, so a broken template fails the deploy, not a request
 *  - prime opcache with them (and opcache.file_cache, when configured, which php-fpm can read)
 *  - write bootstrap/cache/views-warm.php, which tells the view compiler to skip per-render
 *    source mtime checks (production only; like route/config caches, re-run after changing views)
 */
#[AsCommand(name: 'view:warm')]
class ViewWarmCommand extends Command
{
    protected $signature = 'view:warm';

    protected $description = 'Compile, parse-check and opcache-prime every Blade view';

    public function handle(Filesystem $files): int
    {
        if ($this->callSilently('view:cache') !== 0) {
            $this->components->error('view:cache failed; run it directly to see the error.');

            return self::FAILURE;
        }

        $compiledDir = $this->laravel['config']->get('view.compiled');
        $compiled = [];
        $broken = [];

        foreach ($files->glob(rtrim($compiledDir, '\/').'/*.php') as $path) {
            $path = realpath($path) ?: $path;

            Opcache::lint($path) ? $compiled[] = $path : $broken[] = $path;
        }

        foreach ($broken as $path) {
            $this->components->warn('Compiled view does not parse: '.basename($path));
        }

        $manifest = $this->laravel->getCachedViewsManifestPath();
        $files->replace($manifest, '<?php'.PHP_EOL.PHP_EOL.'// Generated by `php artisan view:warm`. Do not edit.'.PHP_EOL.PHP_EOL
            .'return '.var_export(['compiled' => $compiled, 'built' => time()], true).';'.PHP_EOL);

        $this->components->info(sprintf('%d views compiled and parse-checked%s.', count($compiled), $broken ? ', '.count($broken).' broken' : ''));

        $this->components->twoColumnDetail('Manifest', str_replace($this->laravel->basePath().DIRECTORY_SEPARATOR, '', $manifest));
        $this->components->twoColumnDetail('Source mtime checks', $this->laravel['config']->get('app.debug') ? 'on (APP_DEBUG=true)' : 'off (views are warm)');
        $this->components->twoColumnDetail('Opcache (this CLI process)', Opcache::available() ? 'primed' : 'disabled (opcache.enable_cli)');
        $this->components->twoColumnDetail('Opcache file cache', ($dir = Opcache::fileCache()) && Opcache::available() ? 'primed: '.$dir : 'not configured');

        return $broken === [] ? self::SUCCESS : self::FAILURE;
    }
}
