<?php

namespace Nitro\Console;

use Illuminate\Contracts\Container\SelfBuilding;
use Nitro\Foundation\Application;
use ReflectionClass;
use ReflectionNamedType;
use UnitEnum;

/**
 * Compiles container autowiring for the classes a request actually builds (controllers,
 * middleware and their constructor dependencies) into plain `new` expressions, written to
 * bootstrap/cache/factories.php. The container then never reflects on them at runtime.
 *
 * A class is only compiled when the result is provably identical to Container::build():
 * no class or parameter attributes, no variadics, no union types, no contextual bindings,
 * primitives only when they have a default. Everything else keeps using reflection.
 */
final class FactoryCompiler
{
    /** @var array<string, string> class => generated method body */
    private array $compiled = [];

    /** @var array<string, true> */
    private array $visited = [];

    /** @var list<string> */
    public array $skipped = [];

    public function __construct(private readonly Application $app)
    {
    }

    /** @param iterable<string> $classes */
    public function compile(iterable $classes): string
    {
        foreach ($classes as $class) {
            $this->visit(ltrim($class, '\\'));
        }

        $methods = [];
        $map = [];
        $n = 0;

        foreach ($this->compiled as $class => $body) {
            $method = 'f'.$n++;
            $map[$class] = $method;
            $methods[] = "    public function {$method}(\$app, \$params)\n    {\n        if (\$params) {\n            return \$app->build(\\{$class}::class);\n        }\n\n        return {$body};\n    }";
        }

        return "<?php\n\n// Generated by `php artisan route:cache`. Do not edit.\n\nreturn [new class\n{\n".implode("\n\n", $methods)."\n}, ".var_export($map, true)."];\n";
    }

    public function count(): int
    {
        return count($this->compiled);
    }

    private function visit(string $class): bool
    {
        if (isset($this->visited[$class])) {
            return isset($this->compiled[$class]);
        }

        $this->visited[$class] = true;

        // Bound services resolve through their binding; the table must not shadow it.
        if ($this->app->bound($class) || $this->app->isAlias($class) || ! class_exists($class)) {
            return false;
        }

        $reflector = new ReflectionClass($class);

        if (! $reflector->isInstantiable()
            || $reflector->getAttributes() !== []
            || $reflector->implementsInterface(SelfBuilding::class)
            || isset($this->app->contextual[$class])) {
            $this->skipped[] = $class;

            return false;
        }

        $arguments = [];

        foreach ($reflector->getConstructor()?->getParameters() ?? [] as $parameter) {
            $argument = $this->argument($parameter);

            if ($argument === null) {
                $this->skipped[] = $class;

                return false;
            }

            $arguments[] = $argument;
        }

        $this->compiled[$class] = 'new \\'.$class.'('.implode(', ', $arguments).')';

        return true;
    }

    private function argument(\ReflectionParameter $parameter): ?string
    {
        if ($parameter->isVariadic() || $parameter->getAttributes() !== []) {
            return null;
        }

        $type = $parameter->getType();

        if ($type instanceof ReflectionNamedType && ! $type->isBuiltin()) {
            $name = $type->getName();

            if ($name === 'self' || $name === 'static') {
                $name = $parameter->getDeclaringClass()->getName();
            }

            if ($parameter->isDefaultValueAvailable()) {
                // Container::resolveClass(): default wins unless the type is bound.
                return self::exportable($default = $parameter->getDefaultValue())
                    ? "(\$app->bound(\\{$name}::class) ? \$app->make(\\{$name}::class) : ".var_export($default, true).')'
                    : null;
            }

            $this->visit($name);

            return "\$app->make(\\{$name}::class)";
        }

        if ($type !== null && ! $type instanceof ReflectionNamedType) {
            return null; // union / intersection
        }

        return $parameter->isDefaultValueAvailable() && self::exportable($default = $parameter->getDefaultValue())
            ? var_export($default, true)
            : null;
    }

    private static function exportable(mixed $value): bool
    {
        if ($value === null || is_scalar($value) || $value instanceof UnitEnum) {
            return true;
        }

        if (! is_array($value)) {
            return false;
        }

        foreach ($value as $item) {
            if (! self::exportable($item)) {
                return false;
            }
        }

        return true;
    }
}
